export const images = {
  attach: require('../../assets/images/attach.png'),
  call: require('../../assets/images/call.png'),
  camera: require('../../assets/images/camera.png'),
  emoji: require('../../assets/images/emoji.png'),
  grayCamera: require('../../assets/images/grayCamera.png'),
  leftArrow: require('../../assets/images/leftArrow.png'),
  rightArrow: require('../../assets/images/rightArrow.png'),
  messageSend: require('../../assets/images/messageSend.png'),
  MetaAilogo: require('../../assets/images/MetaAilogo.png'),
  mic: require('../../assets/images/mic.png'),
  pencil: require('../../assets/images/pencil.png'),
  search: require('../../assets/images/search.png'),
  threeDots: require('../../assets/images/threeDots.png'),
  videoCall: require('../../assets/images/videoCall.png'),
  wallpaper: require('../../assets/images/wallpaper.jpg'),
  community: require('../../assets/images/community.jpg'),
  whiteCam: require('../../assets/images/whiteCam.png'),
};
